BI_project:
    target: bidb
    outputs:
        bidb:
            type: redshift
            host: bi-dw.cxbumohsmgpg.us-east-2.redshift.amazonaws.com
            user: "{{ env_var('masteradmin') }}"
            password: "{{ env_var('Mario123') }}"
            port: 5439
            dbname: bidb
            schema: derived_datasets
            threads: 4
            keepalives_idle: 240 # default 240 seconds
            connect_timeout: 10 # default 10 seconds
            ra3_node: true